spring:
  application:
    name: chat-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: postgres
  jmx:
    enabled: false
  flyway:
    url: jdbc:postgresql://localhost:5432/chat
    user: postgres
    password: postgres
    enabled: true
    locations:
      - classpath:db/migration
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
        synonyms: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: OSADMIN
        enable_lazy_load_no_trans: true
    show-sql: false
